"""tools/validate_web_contact.py — READ-ONLY Phase-8 live validation harness.

Purpose (VALIDATION ONLY — no feature/architecture changes):
  Runs a SMALL, controlled, READ-ONLY validation of CONTACT_PROVIDER=web_search
  over a tiny set of REAL already-accepted leads (data/runs/*.json). For each
  lead it produces a per-field audit (FIELD/VALUE/SOURCE/EVIDENCE URL/
  CONFIDENCE/STATUS) in both BEFORE (current pipeline, no provider) and AFTER
  (Phase-8 web_search) form, and classifies every field as VERIFIED /
  PARTIALLY VERIFIED / NOT FOUND / CONFLICTING / REJECTED.

SAFETY (enforced here, not just documented):
  - DRY_RUN is NEVER touched (config is imported read-only, never mutated).
  - NEVER writes to Google Sheets, never sets DRY_RUN=false.
  - NEVER modifies the deterministic classifier / gates / dedup / rejection.
  - Email quality: an email reaches the lead ONLY if resolve_email's
    public-business guard accepts it (role-prefix public mailbox like
    careers@/*@official). We NEVER generate first@domain / first.last@domain /
    name@domain. A missing email is preferred over a fabricated one.
  - The web_search provider is constructed DIRECTLY (NOT via env config) with a
    tiny request budget, min-interval throttle and a disk cache, so the live
    footprint stays minimal and is never a permanent config change.
  - Output goes to stdout (and optionally a local JSON report under data/ when
    --out is given). No production artifact is modified.

Usage:
  python tools/validate_web_contact.py                       # small live run
  python tools/validate_web_contact.py --limit 4             # smaller
  python tools/validate_web_contact.py --offline             # no network at all
  python tools/validate_web_contact.py --out data/validation/phase8.json
"""
import argparse
import glob
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.contact import ContactDiscoveryCache, WebSearchContactDiscoveryProvider
from app.enrichment import Enricher

# -- field classification ------------------------------------------------------
SENTINELS = {"Unclear", "Not Available", "Not Specified", "Not Disclosed", ""}
PUBLIC_PREFIXES = ("careers", "hiring", "jobs", "talent", "recruit", "recruiting",
                   "recruitment", "recruiter", "contact", "hello", "info",
                   "apply", "hr", "work", "join", "team")


def guessed_email(email):
    """True if the email looks like a GUESSED first/last@domain that must be
    rejected (never generated by us, but flag if a bad provider slipped one in)."""
    if not email or email in SENTINELS or "@" not in email:
        return False
    local = email.split("@")[0].lower().strip()
    domain = email.split("@")[-1].lower()
    if domain in ("gmail.com", "yahoo.com", "hotmail.com", "outlook.com",
                  "ymail.com", "live.com", "icloud.com", "zoho.com"):
        return True
    # A named local-part with a dot is NOT an approved public prefix -> guess.
    if "." in local and not any(p in local for p in PUBLIC_PREFIXES):
        return True
    return False


def classify(value, evidence_url, confidence):
    if value is None or value in SENTINELS:
        return "NOT_FOUND"
    if evidence_url and confidence and confidence >= 0.6:
        return "VERIFIED"
    if evidence_url or (confidence and confidence >= 0.5):
        return "PARTIALLY VERIFIED"
    return "PARTIALLY VERIFIED"


def load_runs_leads():
    """Return every already-accepted (New/valid) lead record from data/runs."""
    leads = []
    for f in sorted(glob.glob("data/runs/*.json")):
        with open(f, encoding="utf-8") as fh:
            d = json.load(fh)
        if isinstance(d, dict):
            for v in d.values():
                if isinstance(v, list):
                    d = v
                    break
        for rec in (d if isinstance(d, list) else []):
            if not isinstance(rec, dict):
                continue
            st = str(rec.get("status", "")).upper()
            if st in ("NEW", "ACCEPT", "READY") or rec.get("is_valid") is True:
                leads.append(rec)
    return leads


def build_provider(cache_path, max_requests=6):
    return WebSearchContactDiscoveryProvider(
        cache=ContactDiscoveryCache(path=cache_path),
        max_pages=3,
        max_requests=max_requests,
        min_interval_s=0.5,
        timeout_s=8,
    )


def enrich_lead(enricher, lead):
    text = (lead.get("text") or lead.get("post_description")
            or lead.get("original_text") or lead.get("post_snippet") or "").strip()
    if not text:
        return None
    source_link = (lead.get("post_url") or lead.get("source_linkedin_url")
                   or lead.get("url") or "")
    return enricher.enrich(
        post_text=text, source_link=source_link,
        post_date=lead.get("post_date") or lead.get("postedAtISO") or "",
        author_name=lead.get("author_name") or "",
        author_profile_url=lead.get("author_profile_url") or "",
        job_metadata_company=lead.get("company") or "Unclear",
        job_metadata_is_authoritative=False,
        job_card_location=lead.get("location") or "",
        classified_company=(lead.get("company_name") or lead.get("company")
                            or "Unclear"),
        classified_major_category=lead.get("major_category") or "Unclear",
        classified_exact_role=(lead.get("exact_role")
                               or lead.get("detected_role_title") or "Unclear"),
        classified_confidence=float(lead.get("confidence")
                                    or lead.get("confidence_score") or 0.0),
        classified_location=lead.get("location") or "Not Specified",
        classified_employment=lead.get("employment_type") or "Unclear",
        classified_experience=(lead.get("experience_required")
                               or "Not Specified"),
        classified_ctc=lead.get("ctc") or "Not Disclosed",
        classified_india_relevance=lead.get("india_relevance") or "Unclear",
        classified_status=lead.get("status") or "New",
    )


def field_rows(after):
    specs = [
        ("company", after.company_name, after.company_evidence_url, after.company_confidence),
        ("exact_role", after.exact_role, after.role_evidence_snippet, after.role_confidence),
        ("location", after.location, "", after.location_confidence),
        ("employment_type", after.employment_type, "", after.employment_confidence),
        ("experience_required", after.experience_required, "", after.experience_confidence),
        ("ctc", after.ctc, "", after.ctc_confidence),
        ("hiring_manager_name", after.hiring_manager_name,
         after.hiring_manager_evidence_url, after.hiring_manager_confidence),
        ("hiring_manager_linkedin", after.hiring_manager_linkedin,
         after.hiring_manager_evidence_url, after.hiring_manager_confidence),
        ("cold_email", after.cold_email, after.email_evidence_url, after.email_confidence),
        ("email_evidence_url", after.email_evidence_url, "", 1.0),
        ("company_domain", after.company_domain, after.company_evidence_url,
         after.company_confidence),
        ("data_quality_score", after.data_quality_score, "", 1.0),
    ]
    rows = []
    for name, value, evurl, conf in specs:
        st = classify(value, evurl, conf)
        rows.append({"field": name, "value": value, "evidence_url": evurl,
                     "confidence": conf, "status": st})
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=5)
    ap.add_argument("--offset", type=int, default=0)
    ap.add_argument("--offline", action="store_true",
                    help="No network: provider disabled, BEFORE-only audit.")
    ap.add_argument("--out", default="", help="Optional JSON report path.")
    ap.add_argument("--cache", default=(
        r"C:\Users\kartik\AppData\Local\Temp\opencode\contact_cache.json"))
    ap.add_argument("--max-requests", type=int, default=6)
    args = ap.parse_args()

    from app.config import DRY_RUN, CONTACT_PROVIDER  # read-only
    print(f"[validation] config snapshot (read-only, unchanged): "
          f"DRY_RUN={DRY_RUN}  CONTACT_PROVIDER={CONTACT_PROVIDER!r}\n")

    leads = load_runs_leads()
    print(f"[validation] loaded {len(leads)} already-accepted leads from data/runs")

    window = leads[args.offset: args.offset + args.limit]
    provider = None if args.offline else build_provider(args.cache, args.max_requests)
    en_before = Enricher()
    en_after = Enricher(contact_provider=provider)

    summary = {"records": 0, "files_failed": 0,
               "verified_emails": 0, "emails_not_found": 0, "emails_guessed": 0,
               "managers_found": 0, "linkedin_verified": 0,
               "companies_with_domain": 0, "conflicting": 0,
               "false_positives": 0, "hallucinations": 0,
               "dq_scores": [], "web_requests": 0, "cache_hits": 0,
               "cache_misses": 0, "failures": 0, "timeouts": 0}
    led = []

    for i, lead in enumerate(window):
        print("\n" + "=" * 88)
        print(f"LEAD #{i + 1}  url={(lead.get('post_url') or lead.get('source_linkedin_url') or '')[:60]}")
        print("=" * 88)

        try:
            before = enrich_lead(en_before, lead)
            if before is None:
                summary["files_failed"] += 1
                print("  !! no post text; skipped")
                continue
            after = enrich_lead(en_after, lead) if provider else before
        except Exception as exc:
            summary["failures"] += 1
            print(f"  !! enrich failed: {type(exc).__name__}: {exc}")
            continue

        summary["records"] += 1
        print("  BEFORE (current pipeline):")
        print(f"    company={before.company_name!r}  domain={before.company_domain!r}")
        print(f"    role={before.exact_role!r}  loc={before.location!r}  emp={before.employment_type!r}")
        print(f"    exp={before.experience_required!r}  ctc={before.ctc!r}")
        print(f"    manager={before.hiring_manager_name!r}  linkedin={before.hiring_manager_linkedin!r}")
        print(f"    email={before.cold_email!r} (status={before.email_status})  DQ={before.data_quality_score}")

        print("  AFTER (Phase-8 web_search)  discovery=" +
              str(getattr(after, "contact_discovery_status", "NOT_FOUND")))
        print(f"    company={after.company_name!r}  domain={after.company_domain!r}  "
              f"DOMAIN_URL={after.company_evidence_url!r}")
        print(f"    role={after.exact_role!r}  loc={after.location!r}  emp={after.employment_type!r}")
        print(f"    exp={after.experience_required!r}  ctc={after.ctc!r}")
        print(f"    manager={after.hiring_manager_name!r}  linkedin={after.hiring_manager_linkedin!r}")
        print(f"    email={after.cold_email!r} (status={after.email_status})  "
              f"EMAIL_URL={after.email_evidence_url!r}  DQ={after.data_quality_score}")

        rows = field_rows(after)
        print("  -- FIELD AUDIT --")
        print(f"    {'FIELD':<22}{'VALUE':<46}{'STATUS'}")
        for r in rows:
            print(f"    {r['field']:<22}{(str(r['value'])[:44]):<46}{r['status']}")
            if r["evidence_url"]:
                print(f"      EVIDENCE URL = {r['evidence_url']}")
        print(f"    enrichment_status={after.enrichment_status}")

        # tallies
        if after.email_status == "FOUND" and after.cold_email not in SENTINELS:
            if guessed_email(after.cold_email):
                summary["emails_guessed"] += 1
                summary["hallucinations"] += 1
            else:
                summary["verified_emails"] += 1
        else:
            summary["emails_not_found"] += 1
        if after.hiring_manager_name not in SENTINELS:
            summary["managers_found"] += 1
        if after.hiring_manager_linkedin and \
                "linkedin.com/in/" in after.hiring_manager_linkedin:
            summary["linkedin_verified"] += 1
        if after.company_domain and after.company_domain not in SENTINELS:
            summary["companies_with_domain"] += 1
        # conflicting: a resolved domain that clearly does not match the post
        # company (the enricher uses post-text company; if domain differs we
        # flag CONFLICTING for manual review rather than trust it).
        if after.company_domain not in SENTINELS and \
           after.company_name not in SENTINELS:
            base = str(after.company_domain).split(".")[0].lower().replace(" ", "")
            comp = str(after.company_name).lower().replace(" ", "").replace("'", "")
            if base and comp and base not in comp and comp not in base:
                summary["conflicting"] += 1
        dq = float(after.data_quality_score or 0.0)
        summary["dq_scores"].append(dq)
        if dq < 0.3:
            summary["false_positives"] += 1

        led.append({"lead": f"#{i + 1}", "url": (lead.get("post_url")
                    or lead.get("source_linkedin_url") or ""),
                    "company_before": before.company_name,
                    "company_after": after.company_name,
                    "domain": after.company_domain,
                    "domain_url": after.company_evidence_url,
                    "discovery": after.contact_discovery_status,
                    "email": after.cold_email, "email_status": after.email_status,
                    "email_url": after.email_evidence_url,
                    "manager": after.hiring_manager_name,
                    "manager_linkedin": after.hiring_manager_linkedin,
                    "manager_url": after.hiring_manager_evidence_url,
                    "dq": dq, "enrichment_status": after.enrichment_status,
                    "fields": rows})

    if provider is not None:
        summary["web_requests"] = getattr(provider, "request_count", 0)
        summary["cache_hits"] = getattr(provider._cache, "hits", 0)
        summary["cache_misses"] = getattr(provider._cache, "misses", 0)

    n = max(1, summary["records"])
    print("\n" + "=" * 88)
    print("VALIDATION SUMMARY")
    print("=" * 88)
    print(f"  records tested          : {summary['records']}")
    print(f"  verified public emails  : {summary['verified_emails']}")
    print(f"  emails NOT found        : {summary['emails_not_found']}")
    print(f"  emails GUESSED (rej.)   : {summary['emails_guessed']}")
    print(f"  hiring managers found   : {summary['managers_found']}")
    print(f"  LinkedIn URLs verified  : {summary['linkedin_verified']}")
    print(f"  companies w/ domain     : {summary['companies_with_domain']}")
    print(f"  conflicting results     : {summary['conflicting']}")
    print(f"  false positives (low DQ): {summary['false_positives']}")
    print(f"  hallucinations          : {summary['hallucinations']}")
    print(f"  avg data-quality score  : {sum(summary['dq_scores']) / n:.2f}")
    print(f"  web requests used       : {summary['web_requests']}")
    print(f"  cache hits / misses     : {summary['cache_hits']} / {summary['cache_misses']}")
    print(f"  failures / timeouts     : {summary['failures']} / {summary['timeouts']}")

    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        with open(args.out, "w", encoding="utf-8") as fh:
            json.dump({"summary": summary, "leads": led}, fh, indent=2,
                      default=str)
        print(f"\n[validation] wrote read-only report to {args.out}")


if __name__ == "__main__":
    main()
